# Generated by Django 5.0.1 on 2024-02-07 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppAuth', '0007_alter_userprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dialect',
            name='language',
            field=models.ManyToManyField(blank=True, related_name='dialect_language', to='AppAuth.language'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='dialect',
            field=models.ManyToManyField(blank=True, to='AppAuth.dialect'),
        ),
    ]
