# Generated by Django 5.0.1 on 2024-02-09 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppAuth', '0009_alter_userprofile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='accessibilty',
            new_name='accessibility',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='folowers',
            new_name='followers',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='dialect',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='dialects',
            field=models.ManyToManyField(blank=True, related_name='user_profiles', to='AppAuth.dialect'),
        ),
        migrations.AlterField(
            model_name='dialect',
            name='language',
            field=models.ManyToManyField(blank=True, related_name='dialect_languages', to='AppAuth.language'),
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='languages',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='languages',
            field=models.ManyToManyField(blank=True, related_name='user_profiles', to='AppAuth.language'),
        ),
    ]
