version: '3.8'

services:
  backend:
    build: 
      context: .
      dockerfile: DockerFile
    ports:
      - "8000:8000"
    volumes:
      - ./admin:/app
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: admins
      MYSQL_USER: admin
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./dbdata:/var/lib/mysql # Ensure this path is correct and accessible
    ports:
      - "3306:3306"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
