services:
    mongodb:
      image: mongo
      restart: always
      environment:
        MONGO_INITDB_DATABASE: khatira
        MONGO_INITDB_ROOT_USERNAME: admin
        MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
      volumes:
        - ./mongodata:/data/db
      ports:
        - "27017:27017"